In [1]:
import numpy as np

## Introduction

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
two_d = np.array([[1,2,3], [4,5,6]])
two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
three_d = np.array([[[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]])
three_d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
arr.ndim

1

In [11]:
two_d.ndim

2

In [12]:
three_d.ndim

3

In [13]:
high_d = np.array([1,2,3,5], ndmin=5)
high_d

array([[[[[1, 2, 3, 5]]]]])

In [14]:
high_d.ndim

5

## Array Indexing

In [15]:
arr[0]

np.int64(1)

In [16]:
arr[1]

np.int64(2)

In [17]:
print(arr[1])

2


In [19]:
print(two_d[0,1])

2


In [20]:
two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
two_d[1,1]

np.int64(5)

In [22]:
three_d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
three_d[0,0,2]

np.int64(3)

In [25]:
three_d[1,1,2]

np.int64(12)

### Negative indexing

In [26]:
#Last element in 2nd dimension
two_d[1,-1]

np.int64(6)

In [27]:
two_d

array([[1, 2, 3],
       [4, 5, 6]])

## Slicing arrays